const PASSWORD_ACTION_TYPES = {
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_REQUEST_SUCCESS: 'PASSWORD_RESET_REQUEST_SUCCESS',
  PASSWORD_RESET_REQUEST_FAILED: 'PASSWORD_RESET_REQUEST_FAILED',

  PASSWORD_RESET_CONFIRMATION: 'PASSWORD_RESET_CONFIRMATION',
  PASSWORD_RESET_CONFIRMATION_REQUEST: 'PASSWORD_RESET_CONFIRMATION_REQUEST',
  PASSWORD_RESET_CONFIRMATION_REQUEST_SUCCESS: 'PASSWORD_RESET_CONFIRMATION_REQUEST_SUCCESS',
  PASSWORD_RESET_CONFIRMATION_REQUEST_FAILED: 'PASSWORD_RESET_CONFIRMATION_REQUEST_FAILED',
};

export default PASSWORD_ACTION_TYPES;
