const EVENTS_ACTION_TYPES = {
  GET_EVENTS: 'GET_EVENTS',
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
  GET_EVENTS_ERROR: 'GET_EVENTS_ERROR',

  ADD_EVENT: 'ADD_EVENT',
  ADD_EVENT_SUCCESS: 'ADD_EVENT_SUCCESS',
  ADD_EVENT_ERROR: 'ADD_EVENT_ERROR',

  DELETE_EVENT: 'DELETE_EVENT',
  DELETE_EVENT_SUCCESS: 'DELETE_EVENT_SUCCESS',
  DELETE_EVENT_ERROR: 'DELETE_EVENT_ERROR',
};

export default EVENTS_ACTION_TYPES;
