const EDIT_USER_ACTION_TYPES = {

    UPDATE_USER_DATA: "UPDATE_USER_DATA",
    UPDATE_USER_DATA_REQUEST: "UPDATE_USER_DATA_REQUEST",
    UPDATE_USER_DATA_SUCCESS: "UPDATE_USER_DATA_SUCCESS",
    UPDATE_USER_DATA_ERROR: "UPDATE_USER_DATA_ERROR",

};

export default EDIT_USER_ACTION_TYPES;