export const categories = [
  'Aerospace',
  'Agency & Consulting',
  'Agriculture Company',
  'Analytics',
  'Automotive',
  'Bar & Brewery',
  'Beauty & Cosmetics',
  'Beer, Wine & Spirits',
  'Bikes Brand',
  'Biotech',
  'Bots & AI',
  'Cannabis & CBD',
  'Catering',
  'Cleaning',
  'Co-Working Space Names',
  'Coffee & Tea',
  'Community Organization',
  'Companies & Organizations - Industrial Company',
  'Crowdfunding',
  'Cryptocurrency, Blockchain',
  'Dating & Relationship',
  'Daycare',
  'Dental',
  'Drone',
  'E-Commerce & Retail',
  'Education & Training',
  'Entertainment & Arts',
  'Event Planning & Services',
  'Events & Conferences',
  'Fashion & Clothing',
  'Finance',
  'Fintech (Finance Technology)',
  'Fitness & Gym',
  'Food & Drink',
  'Food Delivery & Meal Kits',
  'Food Truck',
  'Footwear',
  'Furniture & Home Furnishings',
  'Games & Recreational',
  'Gaming',
  'Green & Organic',
  'Health & Wellness',
  'Home',
  'Home & Garden',
  'Insurance',
  'Interior Design',
  'Internet of Things (IOT)',
  'Jewelry',
  'Kids & Baby',
  'Landscaping',
  'Legal, Attorney, Law',
  'Life Coach, Motivational',
  'Location Specific / GEO',
  'Manufacturing & Industrial',
  'Marketing & Advertising',
  'Medical & Dental',
  'Mobile App',
  'Mortgage',
  'Movies & TV',
  'Music & Audio',
  'News & Media',
  'Non-Profit & Community',
  'Office & Business Supplies',
  'Oil and Gas',
  'Outdoor & Adventure',
  'Payment',
  'Payroll',
  'Pets',
  'Pharma',
  'Photography',
  'Podcast',
  'Politics/Government',
  'Professional Services',
  'Property Management',
  'Real Estate',
  'Recruitment & Staffing',
  'Restaurants',
  'Sales & Marketing',
  'Science & Engineering',
  'Security',
  'Senior Living and Care',
  'Social & Networking',
  'Solar Power and Green Energy',
  'Something Else',
  'Spas & Salons',
  'Sports',
  'Startup Incubator',
  'Storage',
  'Tech, Internet, Software',
  'Transportation',
  'Travel & Hotel',
  'Tutoring & Test Prep',
  'Venture Capital & Investment',
  'Video, Books & Magazines',
  'Virtual Reality (VR) and Augmented Reality (AR) Company',
  'Vitamins and Supplements',
  'Website & Graphic Design',
  'Weddings & Bridal',
];
