const OFFERS_ACTION_TYPES = {
  GET_OFFERS: 'GET_OFFERS',
  GET_OFFERS_REQUEST: 'GET_OFFERS_REQUEST',
  GET_OFFERS_REQUEST_SUCCESS: 'GET_OFFERS_REQUEST_SUCCESS',
  GET_OFFERS_REQUEST_FAILED: 'GET_OFFERS_REQUEST_FAILED',
};

export default OFFERS_ACTION_TYPES;
